
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package JFLEX_Y_CUP;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 33;
  public static final int EXTRA = 15;
  public static final int PABIERTO = 23;
  public static final int CABIERTO = 30;
  public static final int TIPO = 11;
  public static final int POR = 21;
  public static final int PUNTOYCOMA = 18;
  public static final int LLABIERTO = 27;
  public static final int UNIR = 10;
  public static final int PIE = 4;
  public static final int PORCENTAJE = 13;
  public static final int ETIQUETAS = 8;
  public static final int LETRAS = 34;
  public static final int EJEY = 7;
  public static final int EJEX = 6;
  public static final int BARRAS = 3;
  public static final int DIVIDIDO = 22;
  public static final int TITULO = 5;
  public static final int CORCERRADO = 26;
  public static final int DECIMAL = 35;
  public static final int EOF = 0;
  public static final int VALORES = 9;
  public static final int error = 1;
  public static final int COMILLA = 29;
  public static final int COMA = 17;
  public static final int CADENA = 36;
  public static final int COMENTARIO = 32;
  public static final int MENOS = 20;
  public static final int TOTAL = 14;
  public static final int PCERRADO = 24;
  public static final int CCERRADO = 31;
  public static final int PUNTO = 16;
  public static final int LLCERRADO = 28;
  public static final int CORABIERTO = 25;
  public static final int CANTIDAD = 12;
  public static final int DEF = 2;
  public static final int MAS = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "CANTIDAD",
  "PORCENTAJE",
  "TOTAL",
  "EXTRA",
  "PUNTO",
  "COMA",
  "PUNTOYCOMA",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "PABIERTO",
  "PCERRADO",
  "CORABIERTO",
  "CORCERRADO",
  "LLABIERTO",
  "LLCERRADO",
  "COMILLA",
  "CABIERTO",
  "CCERRADO",
  "COMENTARIO",
  "NUMERO",
  "LETRAS",
  "DECIMAL",
  "CADENA"
  };
}

