
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.practica1_kotlin.JFLEX_Y_CUP;

import com.example.practica1_kotlin.Instrucciones.ErrorObjeto;
import java.util.ArrayList;
import java_cup.runtime.Scanner;
import java_cup.runtime.Symbol;
import java_cup.runtime.SymbolFactory;
import java_cup.runtime.lr_parser;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class AnalizadorSintactico extends lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public AnalizadorSintactico() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public AnalizadorSintactico(Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintactico(Scanner s, SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\057\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\002\004\000\002\014\005\000\002\014\005" +
    "\000\002\014\004\000\002\003\006\000\002\003\010\000" +
    "\002\003\010\000\002\003\010\000\002\003\003\000\002" +
    "\003\004\000\002\004\006\000\002\004\006\000\002\004" +
    "\010\000\002\004\010\000\002\004\006\000\002\004\010" +
    "\000\002\004\006\000\002\004\003\000\002\004\004\000" +
    "\002\012\003\000\002\012\003\000\002\012\004\000\002" +
    "\013\005\000\002\013\003\000\002\013\004\000\002\011" +
    "\011\000\002\011\007\000\002\011\004\000\002\005\005" +
    "\000\002\005\003\000\002\006\003\000\002\006\004\000" +
    "\002\006\003\000\002\006\004\000\002\007\005\000\002" +
    "\007\004\000\002\007\007\000\002\010\003\000\002\010" +
    "\003\000\002\010\003\000\002\010\003\000\002\015\005" +
    "\000\002\015\003\000\002\015\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\167\000\006\003\004\004\005\001\002\000\006\003" +
    "\004\004\005\001\002\000\010\003\010\005\011\006\013" +
    "\001\002\000\004\002\007\001\002\000\004\002\001\001" +
    "\002\000\010\003\010\005\011\006\013\001\002\000\004" +
    "\035\113\001\002\000\010\002\uffff\003\004\004\005\001" +
    "\002\000\004\035\014\001\002\000\024\003\022\007\015" +
    "\012\025\013\020\014\024\015\021\020\017\021\026\036" +
    "\016\001\002\000\004\045\107\001\002\000\010\002\uffed" +
    "\003\uffed\004\uffed\001\002\000\004\043\104\001\002\000" +
    "\004\033\072\001\002\000\010\003\064\016\063\017\065" +
    "\001\002\000\024\003\022\007\015\012\025\013\020\014" +
    "\024\015\021\020\017\021\026\036\016\001\002\000\010" +
    "\002\ufffc\003\ufffc\004\ufffc\001\002\000\004\033\044\001" +
    "\002\000\004\033\032\001\002\000\004\045\027\001\002" +
    "\000\004\024\030\001\002\000\024\003\022\007\015\012" +
    "\025\013\020\014\024\015\021\020\017\021\026\036\016" +
    "\001\002\000\010\002\uffee\003\uffee\004\uffee\001\002\000" +
    "\006\003\033\045\035\001\002\000\006\003\033\045\035" +
    "\001\002\000\004\034\040\001\002\000\006\023\036\034" +
    "\uffd4\001\002\000\006\003\033\045\035\001\002\000\004" +
    "\034\uffd5\001\002\000\004\024\041\001\002\000\024\003" +
    "\022\007\015\012\025\013\020\014\024\015\021\020\017" +
    "\021\026\036\016\001\002\000\010\002\ufff2\003\ufff2\004" +
    "\ufff2\001\002\000\004\034\uffd3\001\002\000\006\003\045" +
    "\035\047\001\002\000\006\003\045\035\047\001\002\000" +
    "\004\034\056\001\002\000\004\043\050\001\002\000\004" +
    "\023\051\001\002\000\004\043\052\001\002\000\004\036" +
    "\053\001\002\000\006\023\054\034\uffe4\001\002\000\006" +
    "\003\045\035\047\001\002\000\004\034\uffe5\001\002\000" +
    "\004\024\057\001\002\000\024\003\022\007\015\012\025" +
    "\013\020\014\024\015\021\020\017\021\026\036\016\001" +
    "\002\000\010\002\uffef\003\uffef\004\uffef\001\002\000\004" +
    "\034\uffe3\001\002\000\010\002\uffec\003\uffec\004\uffec\001" +
    "\002\000\004\024\uffeb\001\002\000\010\003\064\016\063" +
    "\017\065\001\002\000\004\024\uffea\001\002\000\004\024" +
    "\067\001\002\000\024\003\022\007\015\012\025\013\020" +
    "\014\024\015\021\020\017\021\026\036\016\001\002\000" +
    "\010\002\ufff3\003\ufff3\004\ufff3\001\002\000\004\024\uffe9" +
    "\001\002\000\006\003\075\043\074\001\002\000\004\034" +
    "\101\001\002\000\006\023\077\034\uffe7\001\002\000\006" +
    "\003\075\043\074\001\002\000\004\034\uffe6\001\002\000" +
    "\006\003\075\043\074\001\002\000\004\034\uffe8\001\002" +
    "\000\004\024\102\001\002\000\024\003\022\007\015\012" +
    "\025\013\020\014\024\015\021\020\017\021\026\036\016" +
    "\001\002\000\010\002\ufff1\003\ufff1\004\ufff1\001\002\000" +
    "\004\024\105\001\002\000\024\003\022\007\015\012\025" +
    "\013\020\014\024\015\021\020\017\021\026\036\016\001" +
    "\002\000\010\002\ufff0\003\ufff0\004\ufff0\001\002\000\004" +
    "\024\110\001\002\000\024\003\022\007\015\012\025\013" +
    "\020\014\024\015\021\020\017\021\026\036\016\001\002" +
    "\000\010\002\ufff4\003\ufff4\004\ufff4\001\002\000\004\002" +
    "\000\001\002\000\016\003\117\007\114\010\122\011\121" +
    "\014\116\036\120\001\002\000\004\045\165\001\002\000" +
    "\010\002\ufffd\003\ufffd\004\ufffd\001\002\000\004\033\160" +
    "\001\002\000\016\003\117\007\114\010\122\011\121\014" +
    "\116\036\120\001\002\000\010\002\ufff6\003\ufff6\004\ufff6" +
    "\001\002\000\004\033\130\001\002\000\004\033\123\001" +
    "\002\000\006\003\033\045\035\001\002\000\004\034\125" +
    "\001\002\000\004\024\126\001\002\000\016\003\117\007" +
    "\114\010\122\011\121\014\116\036\120\001\002\000\010" +
    "\002\ufff9\003\ufff9\004\ufff9\001\002\000\006\043\131\044" +
    "\134\001\002\000\016\023\uffe0\025\135\026\137\027\141" +
    "\030\140\034\uffe0\001\002\000\006\023\154\034\uffe1\001" +
    "\002\000\004\034\151\001\002\000\016\023\uffde\025\135" +
    "\026\137\027\141\030\140\034\uffde\001\002\000\006\031" +
    "\uffd9\043\uffd9\001\002\000\006\023\uffdd\034\uffdd\001\002" +
    "\000\006\031\uffd8\043\uffd8\001\002\000\006\031\uffd6\043" +
    "\uffd6\001\002\000\006\031\uffd7\043\uffd7\001\002\000\006" +
    "\031\144\043\143\001\002\000\020\023\uffdb\025\135\026" +
    "\137\027\141\030\140\032\uffdb\034\uffdb\001\002\000\004" +
    "\043\145\001\002\000\012\025\135\026\137\027\141\030" +
    "\140\001\002\000\004\032\147\001\002\000\010\023\uffda" +
    "\032\uffda\034\uffda\001\002\000\010\023\uffdc\032\uffdc\034" +
    "\uffdc\001\002\000\004\024\152\001\002\000\016\003\117" +
    "\007\114\010\122\011\121\014\116\036\120\001\002\000" +
    "\010\002\ufff8\003\ufff8\004\ufff8\001\002\000\006\043\131" +
    "\044\134\001\002\000\004\034\uffe2\001\002\000\006\023" +
    "\uffdf\034\uffdf\001\002\000\010\002\ufff5\003\ufff5\004\ufff5" +
    "\001\002\000\006\003\045\035\047\001\002\000\004\034" +
    "\162\001\002\000\004\024\163\001\002\000\016\003\117" +
    "\007\114\010\122\011\121\014\116\036\120\001\002\000" +
    "\010\002\ufff7\003\ufff7\004\ufff7\001\002\000\004\024\166" +
    "\001\002\000\016\003\117\007\114\010\122\011\121\014" +
    "\116\036\120\001\002\000\010\002\ufffa\003\ufffa\004\ufffa" +
    "\001\002\000\010\002\ufffb\003\ufffb\004\ufffb\001\002\000" +
    "\004\002\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\167\000\004\002\005\001\001\000\004\002\170\001" +
    "\001\000\004\014\011\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\014\167\001\001\000\002\001\001\000" +
    "\004\002\111\001\001\000\002\001\001\000\004\004\022" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\012\065\001\001\000\004" +
    "\004\061\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\030\001\001\000\002\001\001\000\004\015\033\001" +
    "\001\000\004\015\042\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\015\036\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\041\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\045\001\001\000\004\011" +
    "\060\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\011\054\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\004\057\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\012\070\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\004\067\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\013\072\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\013\075\001\001\000\002\001\001\000\004" +
    "\013\077\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\004\102\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\004\105\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\004\110\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\003\114\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\156\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\015\123\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\003\126\001\001\000\002\001\001\000\006\005" +
    "\132\006\131\001\001\000\006\007\155\010\141\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\007\135\010" +
    "\141\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\007\147\010\141\001\001\000\002\001\001" +
    "\000\006\007\145\010\141\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\003\152\001\001\000\002\001\001\000\006\005\154\006" +
    "\131\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\011\160\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\003\163\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\003\166\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public Symbol do_action(
    int                        act_num,
    lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




private Symbol s;
ArrayList<String> temp = new ArrayList<>();
ArrayList<ArrayList> instrucciones = new ArrayList<>();
ArrayList<ErrorObjeto> errores = new ArrayList<>();

public AnalizadorSintactico(AnalizadorLexico lexico){
    super(lexico);
}

public Symbol getS(){
return this.s;
}

public ArrayList<ErrorObjeto> getErrores() {
        return errores;
    }

public void setErrores(ArrayList<ErrorObjeto> errores) {
        this.errores = errores;
    }

    public ArrayList<String> getTemp() {
        return temp;
    }

    public void setTemp(ArrayList<String> temp) {
        this.temp = temp;
    }

    public ArrayList<ArrayList> getInstrucciones() {
        return instrucciones;
    }

    public void setInstrucciones(ArrayList<ArrayList> instrucciones) {
        this.instrucciones = instrucciones;
    }


    private void añadirString(String dato) {
        temp.add(dato);
    }
    
    private void reiniciarTemp() {
        if (temp.size() != 0) {
            instrucciones.add(temp);
        }
        temp = new ArrayList<>();
    }
         
 //tratamiento de errores
    public void report_error(String message, Object info) {
        System.out.println("public void report_error");
    }
    
    public void report_fatal_error(String message, Object info) {
        System.out.println("public void report_fatal_error");
    }

    public void syntax_error(Symbol cur_token) {
        System.out.println("El error es el simbolo: " + sym.terminalNames[cur_token.sym]);
        System.out.println(String.format("En la posicion: %d, %d", cur_token.left, cur_token.right));
        errores.add(new ErrorObjeto((String)cur_token.value, "Sintactico","Se esperaba ‘graficar’ o ‘animar’",cur_token.left, cur_token.right));
        System.out.println("Error guardado");
    }

    public void unrecovered_syntax_error(Symbol cur_token) {
         if (cur_token.sym == sym.EOF) {
System.out.println("unrecovered_syntax_error");
            System.out.println("El error es el simbolo: " + (String)cur_token.value);
            System.out.println(String.format("En la posicion: %d, %d", cur_token.left, cur_token.right));
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$AnalizadorSintactico$actions {
  private final AnalizadorSintactico parser;

  /** Constructor */
  CUP$AnalizadorSintactico$actions(AnalizadorSintactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final Symbol CUP$AnalizadorSintactico$do_action_part00000000(
    int                        CUP$AnalizadorSintactico$act_num,
    lr_parser CUP$AnalizadorSintactico$parser,
    java.util.Stack            CUP$AnalizadorSintactico$stack,
    int                        CUP$AnalizadorSintactico$top)
    throws Exception
    {
      /* Symbol object for return from actions */
      Symbol CUP$AnalizadorSintactico$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= n EOF 
            {
              Object RESULT =null;
		int start_valleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int start_valright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Object start_val = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintactico$parser.done_parsing();
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // n ::= DEF bp n 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("n",0, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // n ::= DEF bp 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("n",0, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // n ::= error n 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("n",0, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // bp ::= BARRAS LLABIERTO s3 
            {
              Object RESULT =null;
		int bleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int bright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		Object b = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		añadirString((String)b);reiniciarTemp();
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("bp",10, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // bp ::= PIE LLABIERTO s4 
            {
              Object RESULT =null;
		int pleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int pright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		Object p = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		añadirString((String)p);reiniciarTemp();
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("bp",10, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // bp ::= error bp 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("bp",10, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // s3 ::= TITULO CADENA PUNTOYCOMA s3 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		añadirString("T"+"\n"+ (String)c);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s3",1, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // s3 ::= EJEX CORABIERTO i CORCERRADO PUNTOYCOMA s3 
            {
              Object RESULT =null;
		int eleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int eright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		Object e = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		añadirString("X"+"\n"+(String)e);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s3",1, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-5)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // s3 ::= EJEY CORABIERTO f CORCERRADO PUNTOYCOMA s3 
            {
              Object RESULT =null;
		int dleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int dright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		Object d = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		añadirString("Y"+"\n"+(String)d);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s3",1, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-5)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // s3 ::= UNIR CORABIERTO g CORCERRADO PUNTOYCOMA s3 
            {
              Object RESULT =null;
		int xleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int xright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		Object x = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		añadirString(("U"+"\n"+(String)x));
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s3",1, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-5)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // s3 ::= LLCERRADO 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s3",1, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // s3 ::= error s3 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s3",1, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // s4 ::= TITULO CADENA PUNTOYCOMA s4 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		añadirString("T"+"\n"+ (String)c);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s4",2, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // s4 ::= TIPO cp PUNTOYCOMA s4 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		añadirString("O"+"\n"+ (String)c);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s4",2, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // s4 ::= ETIQUETAS CORABIERTO i CORCERRADO PUNTOYCOMA s4 
            {
              Object RESULT =null;
		int eleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int eright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		Object e = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		añadirString("E"+"\n"+(String)e);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s4",2, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-5)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // s4 ::= VALORES CORABIERTO m CORCERRADO PUNTOYCOMA s4 
            {
              Object RESULT =null;
		int eleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int eright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		Object e = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		añadirString("V"+"\n"+(String)e);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s4",2, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-5)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // s4 ::= TOTAL NUMERO PUNTOYCOMA s4 
            {
              Object RESULT =null;
		int eleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int eright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		Object e = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		añadirString("L"+"\n"+(String)e);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s4",2, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // s4 ::= UNIR CORABIERTO g CORCERRADO PUNTOYCOMA s4 
            {
              Object RESULT =null;
		int eleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int eright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		Object e = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		añadirString("U"+"\n"+(String)e);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s4",2, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-5)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // s4 ::= EXTRA CADENA PUNTOYCOMA s4 
            {
              Object RESULT =null;
		int eleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int eright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		Object e = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		añadirString("A"+"\n"+(String)e);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s4",2, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // s4 ::= LLCERRADO 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s4",2, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // s4 ::= error s4 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("s4",2, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // cp ::= CANTIDAD 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = String.format("%s",c+"\n");
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("cp",8, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // cp ::= PORCENTAJE 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = String.format("%s",c+"\n");
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("cp",8, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // cp ::= error cp 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("cp",8, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // m ::= NUMERO COMA m 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int coleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int coright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Object co = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		int eleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object e = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 String cadena = (String)c +(String)co +"\n"+ (String)e; RESULT = cadena;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("m",9, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // m ::= NUMERO 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = String.format("%s",c+"\n");
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("m",9, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // m ::= error m 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("m",9, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // g ::= LLABIERTO NUMERO COMA NUMERO LLCERRADO COMA g 
            {
              Object RESULT =null;
		int num1left = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-5)).left;
		int num1right = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-5)).right;
		Object num1 = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-5)).value;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).value;
		int num2left = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int num2right = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		Object num2 = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		int eleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object e = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 String cadena = (String)num1 + (String)c +(String)num2 +"\n"+","+ (String)e; RESULT = cadena;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("g",7, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-6)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // g ::= LLABIERTO NUMERO COMA NUMERO LLCERRADO 
            {
              Object RESULT =null;
		int num1left = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int num1right = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		Object num1 = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int num2left = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int num2right = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Object num2 = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		 String cadena = (String)num1+(String)c+(String)num2+"\n" ; RESULT = cadena;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("g",7, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // g ::= error g 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("g",7, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // f ::= v COMA f 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int coleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int coright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Object co = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		int eleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object e = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 String cadena = (String)c +(String)co +"\n"+ (String)e; RESULT = cadena;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("f",3, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // f ::= v 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = String.format("%s",c+"\n");
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("f",3, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // v ::= NUMERO 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = String.format("%s",c);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("v",4, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // v ::= NUMERO u 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		int eleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object e = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 String cadena = (String)c + (String)e; RESULT = cadena;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("v",4, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // v ::= DECIMAL 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = String.format("%s",c);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("v",4, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // v ::= DECIMAL u 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		int eleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object e = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 String cadena = (String)c + (String)e; RESULT = cadena;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("v",4, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // u ::= o NUMERO u 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int coleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int coright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Object co = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		int eleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object e = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 String cadena = (String)c +(String)co + (String)e; RESULT = cadena;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("u",5, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // u ::= o NUMERO 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		int coleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int coright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object co = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 String cadena = (String)c +(String)co; RESULT = cadena;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("u",5, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // u ::= o PABIERTO NUMERO u PCERRADO 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).value;
		int paleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int paright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		Object pa = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		int xleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int xright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		Object x = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int eleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int eright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Object e = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		int pcleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int pcright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object pc = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 String cadena = (String)c +(String)pa+(String)x +(String)e +(String)pc; RESULT = cadena;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("u",5, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // o ::= MAS 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = String.format("%s",c);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("o",6, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // o ::= MENOS 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = String.format("%s",c);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("o",6, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // o ::= POR 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = String.format("%s",c);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("o",6, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // o ::= DIVIDIDO 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = String.format("%s",c);
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("o",6, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // i ::= CADENA COMA i 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int coleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int coright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Object co = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		int eleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object e = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 String cadena = (String)c +(String)co +"\n"+ (String)e; RESULT = cadena;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("i",11, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // i ::= CADENA 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int cright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object c = (Object)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = String.format("%s",c+"\n");
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("i",11, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // i ::= error i 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("i",11, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$AnalizadorSintactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final Symbol CUP$AnalizadorSintactico$do_action(
    int                        CUP$AnalizadorSintactico$act_num,
    lr_parser CUP$AnalizadorSintactico$parser,
    java.util.Stack            CUP$AnalizadorSintactico$stack,
    int                        CUP$AnalizadorSintactico$top)
    throws Exception
    {
              return CUP$AnalizadorSintactico$do_action_part00000000(
                               CUP$AnalizadorSintactico$act_num,
                               CUP$AnalizadorSintactico$parser,
                               CUP$AnalizadorSintactico$stack,
                               CUP$AnalizadorSintactico$top);
    }
}

}
